import Config

# Configure your database
config :realtime, Realtime.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "realtime_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :realtime, RealtimeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "T85d9dpkmxmO5ayX9XftgAODGh1k8j/ez7IOc5ydbqUME/dCaTN1dD+B0xCrpEp9",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    node: [
      "node_modules/@marp-team/marp-cli/marp-cli.js",
      "-w",
      "--html",
      "true",
      "--notes",
      "true",
      "-I",
      "./",
      "-o",
      Path.expand("../priv/static/slides/", __DIR__),
      cd: Path.expand("../slides", __DIR__)
    ],
    asset_copy: {Phoenix.Copy, :watch, [:slide_images]}
  ]

config :phoenix_copy,
  slide_images: [
    source: Path.expand("../slides/images", __DIR__),
    destination: Path.expand("../priv/static/slides/images", __DIR__)
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :realtime, RealtimeWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg.html)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/realtime_web/(live|views)/.*(ex)$",
      ~r"lib/realtime_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
